"""Regression coverage for the Bob/Hermes startup self-dirty fix (2026-09-01).

Proven defect: scripts/session-start.sh treated the tracked HANDOFF.md as a
generated runtime snapshot and rewrote it with a fresh "Last loaded: <now>"
timestamp on every routine startup, so any Bob session deterministically
dirtied the canonical hermes-config checkout. The fix (chosen ownership
model A — "tracked durable HANDOFF; startup never rewrites it") removes the
write entirely; session-start.sh now only *prints* its orientation snapshot.

These tests exercise the real scripts/session-start.sh source (not a copy)
against a disposable ``$HOME``/git fixture, so they fail red against the old
behavior (which opened HANDOFF_PATH for writing on every run) and pass green
against the fix.
"""

from __future__ import annotations

import io
import os
import subprocess
import sys
import types
import unittest
from contextlib import redirect_stdout
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SESSION_START = REPO / "scripts" / "session-start.sh"

sys.path.insert(0, str(REPO / "scripts"))


def run(cmd, cwd=None, check=True):
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if check and proc.returncode != 0:
        raise AssertionError(f"{cmd} failed: {proc.stdout}\n{proc.stderr}")
    return proc


class SessionStartSelfDirtyTests(unittest.TestCase):
    """H1/H2/H3: routine startup generation never dirties tracked files."""

    def setUp(self):
        self.tmp = self._make_tmp_dir()
        self.home = self.tmp / "home"
        self.hermes = self.home / ".hermes"
        self.hermes.mkdir(parents=True)
        (self.hermes / "scripts").mkdir()

        # Minimal stand-in for the live homelab facts file session-start.sh
        # excerpts from — never written by session-start.sh itself.
        (self.home / "ACERSERVER.md").write_text(
            "# ACERSERVER\n\n"
            "## Server Facts\n- Host: test-fixture\n\n"
            "## Active Agents\n- Bob: test\n\n"
            "## Source of Truth\n- Operating standard: ACP Rule 00-90\n\n"
            "## Recent Activity\n- fixture setup\n",
            encoding="utf-8",
        )

        # Stub for ~/.hermes/scripts/project_status.py (a separate, untracked
        # live runtime script — not part of this repo's checkout).
        (self.hermes / "scripts" / "project_status.py").write_text(
            "import sys\nsys.exit(0)\n", encoding="utf-8"
        )

        # Disposable git repo standing in for the canonical hermes-config
        # checkout, with the full initial fixture tree (including tracked
        # HANDOFF.md) committed — mirrors the real repo's ownership contract
        # (HANDOFF.md tracked + durable) and gives a clean starting baseline.
        self.handoff_path = self.hermes / "HANDOFF.md"
        self.handoff_path.write_text(
            "# HANDOFF — hermes-config\n\n"
            "Durable, hand-maintained task handoff. Not regenerated by "
            "session-start.sh.\n",
            encoding="utf-8",
        )
        run(["git", "init", "-q"], cwd=self.hermes)
        run(["git", "config", "user.email", "test@example.com"], cwd=self.hermes)
        run(["git", "config", "user.name", "Test"], cwd=self.hermes)
        run(["git", "add", "-A"], cwd=self.hermes)
        run(["git", "commit", "-q", "-m", "seed fixture tree"], cwd=self.hermes)

    def _make_tmp_dir(self) -> Path:
        import tempfile

        d = tempfile.TemporaryDirectory()
        self.addCleanup(d.cleanup)
        return Path(d.name)

    def _git_status(self) -> str:
        return run(["git", "status", "--porcelain"], cwd=self.hermes).stdout

    def _run_session_start(self, now: datetime, argv: list[str] | None = None) -> str:
        """Execute the real session-start.sh source in-process with a fake
        clock and an isolated $HOME, so H1's "different clocks" requirement
        is a real, controlled variable rather than incidental timing."""
        argv = argv or []
        source = SESSION_START.read_text(encoding="utf-8")
        code = compile(source, str(SESSION_START), "exec")

        fake_datetime_mod = types.ModuleType("datetime")

        class _FakeDateTime:
            @staticmethod
            def now(tz=None):
                return now

        fake_datetime_mod.datetime = _FakeDateTime

        old_home = os.environ.get("HOME")
        old_argv = sys.argv
        old_datetime_mod = sys.modules.get("datetime")
        old_cwd = os.getcwd()
        old_sys_path = list(sys.path)
        stdout = io.StringIO()
        try:
            os.environ["HOME"] = str(self.home)
            sys.argv = ["session-start.sh"] + argv
            sys.modules["datetime"] = fake_datetime_mod
            os.chdir(SESSION_START.parent)
            sys.path.insert(0, str(SESSION_START.parent))
            with redirect_stdout(stdout):
                exec(code, {"__name__": "__main__", "__file__": str(SESSION_START)})
        finally:
            if old_home is None:
                os.environ.pop("HOME", None)
            else:
                os.environ["HOME"] = old_home
            sys.argv = old_argv
            if old_datetime_mod is not None:
                sys.modules["datetime"] = old_datetime_mod
            else:
                sys.modules.pop("datetime", None)
            os.chdir(old_cwd)
            sys.path[:] = old_sys_path
        return stdout.getvalue()

    def test_h1_different_clocks_never_modify_tracked_handoff(self):
        original_bytes = self.handoff_path.read_bytes()
        original_committed = run(
            ["git", "show", "HEAD:HANDOFF.md"], cwd=self.hermes
        ).stdout

        out_a = self._run_session_start(datetime(2020, 1, 1, 9, 0))
        after_first = self.handoff_path.read_bytes()
        out_b = self._run_session_start(datetime(2099, 12, 31, 23, 59))
        after_second = self.handoff_path.read_bytes()

        self.assertEqual(original_bytes, after_first)
        self.assertEqual(original_bytes, after_second)
        self.assertEqual(original_committed.encode("utf-8"), original_bytes)
        # The fake clock really did change between runs (proves this isn't
        # a same-timestamp coincidence) even though the tracked file didn't.
        self.assertIn("2020-01-01", out_a)
        self.assertIn("2099-12-31", out_b)
        self.assertEqual(self._git_status(), "")

    def test_h2_routine_generation_leaves_git_status_clean(self):
        self._run_session_start(datetime.now())
        self.assertEqual(self._git_status(), "")

    def test_h3_output_includes_rule_00_90_and_orientation(self):
        out = self._run_session_start(datetime.now())
        self.assertIn("ACP Rule 00-90", out)
        self.assertNotIn("ACP Rule 00-80", out)
        self.assertIn("/home/chris/bin/agent-bootstrap", out)
        self.assertIn("AGENTS.md", out)
        self.assertIn("HANDOFF.md", out)

    def test_source_never_opens_handoff_path_for_write(self):
        """Static guard: catches any regression that reintroduces the write."""
        source = SESSION_START.read_text(encoding="utf-8")
        self.assertNotIn('open(HANDOFF_PATH, "w")', source)
        self.assertNotIn("open(HANDOFF_PATH, 'w')", source)


class HandoffOwnershipCoherenceTests(unittest.TestCase):
    """H6: HANDOFF.md/STARTUP_CONTRACT.md describe one coherent durable role."""

    def test_tracked_handoff_is_not_described_as_a_timestamped_snapshot(self):
        content = (REPO / "HANDOFF.md").read_text(encoding="utf-8")
        self.assertNotIn("Last loaded:", content)
        self.assertIn("Durable", content)
        self.assertIn("never writes this file", content)

    def test_startup_contract_no_longer_calls_handoff_generated(self):
        content = (REPO / "STARTUP_CONTRACT.md").read_text(encoding="utf-8")
        self.assertNotIn("Generated `~/.hermes/HANDOFF.md`", content)
        self.assertIn("durable", content.lower())

    def test_sot_wording_preserved(self):
        content = (REPO / "HANDOFF.md").read_text(encoding="utf-8")
        self.assertIn("ACP Rule 00-90", content)
        self.assertIn("/home/chris/bin/agent-bootstrap", content)
        self.assertIn(
            "~/todo.md is the primary global open-work surface", content
        )
        self.assertIn(
            "~/project-status.md is a generated secondary cross-project view",
            content,
        )


if __name__ == "__main__":
    unittest.main()
